What is numpy?
Numpy= numerical python

It is used for:

Fast mathematical operations
Working with large datasets
Scientific computing

In [2]:
import numpy as np


Python list vs numpy Array

numbers=[1,2,3,4]
data=[1,"hello",3.5]

-can store different datatypes
-stored in scattered memory
-slower for larger calculations

numpy array:
arr=np.array([1,2,3,4])

-stores same datatype
-stored in continuous memory
-much faster
-supports mathematical operations


Memory difference:

python list                              NumPy Array
-----------                             -------------
-flexible                             -fixed data type
-slower                               -faster
-different types allowed              -same type only
-memory scattered                     -memory is continuous


In [3]:
#ndarray- (N-dimensional array)
arr=np.array([1,2,3,4])
print(arr * 2)

#normal list
numbers=[1,2,3,4]
print(numbers * 2)

[2 4 6 8]
[1, 2, 3, 4, 1, 2, 3, 4]


In [ ]:
#converting list to array
arr=np.array([10,20,30])
print(arr)

#2D example

arr1=np.array([[1,2,3],
              [4,5,6]])
print(arr1)

[10 20 30]
[[1 2 3]
 [4 5 6]]


In [ ]:
#np.zeros
#creates array filled with zeros

arr=np.zeros(5)
print(arr)

#array with 2 rows,3 columns of zeros
arr1=np.zeros((2,3))
print(arr1)

[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#np.arange
#similar to range function

np.arange(0,10,2)

#(start,stop,step)

array([0, 2, 4, 6, 8])

In [ ]:
#np.linspace
#creates evenly spaced numbers

print(np.linspace(0,10,5))

#(start,stop,number_of_values)

#logspace
#evenly spaced log values
print(np.logspace(1,3,3))

[ 0.   2.5  5.   7.5 10. ]
[  10.  100. 1000.]


In [ ]:
#np.ones()

arr=np.ones(5)
print(arr)

np.ones((2,3))
#2 rows,3 columns

#use when you need default values of 1

[1. 1. 1. 1. 1.]


array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#np.full

print(np.full(5,7))  #one dimensional

print(np.full((2,3),7))
#(shape,fill_value,[dtype]) here dtype is optional

print(np.full((2,2),5,float))

print(np.full((3,3),True))

print(np.full((3,2),"NA")) #used when marking missing categorical values

#creates an array filled with any specific value
#useful for initialization

[7 7 7 7 7]
[[7 7 7]
 [7 7 7]]
[[5. 5.]
 [5. 5.]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[['NA' 'NA']
 ['NA' 'NA']
 ['NA' 'NA']]


In [16]:
#if all 5 students get a bonus marks of 2

marks=np.array([80,75,90,85,88])
bonus=np.full(marks.shape,2)

final_marks=marks+bonus
print(final_marks)

[82 77 92 87 90]


In [ ]:
#np.eye
#creates identity matrix (diagonal=1)

print(np.eye(3))

print(np.diag([1,2,3]))
#create diagonal matrix


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [22]:
#np.random
#creates an array of random numbers between 0 and 1

print(np.random.rand(3))

print(np.random.rand(2,3))

print(np.random.randint(1,10,5))
#creates 5 random numbers between 1 and 9

#random choice
colors=["red","blue","orange","green"]
print(np.random.choice(colors))

#multiple selection
print(np.random.choice(colors,size=5))

[0.51817106 0.20002741 0.51254202]
[[0.307373   0.19544256 0.81188449]
 [0.73713148 0.43350348 0.4771831 ]]
[1 4 5 3 1]
red
['red' 'red' 'blue' 'red' 'blue']


#BROADCASTING

broadcasting allows operations between arrays of different shapes

broad casting rules-
Two arrays are compatible if:

1. They have same shape
    or

2. One of them is 1
    or

3. Smaller array can stretch to match larger


In [ ]:
arr=np.array([1,2,3])

print(arr+5)

[6 7 8]


In [26]:
#broadcasting 1D with 2D

arr=np.array([[1,2,3],
             [4,5,6]])

b=np.array([10,20,30])

print(arr+b)

[[11 22 33]
 [14 25 36]]


In [ ]:
a=np.array(([1,2,5],
           [4,5,6]))

b=np.array([1,2])
print(a+b)

#broadcasting fails

[[2 4]
 [5 7]]


In [ ]:
#column broadcasting

arr=np.array([[1,2,3],
              [4,5,6]])

col=np.array([[10],
             [20]])
print(arr+col)

[[11 12 13]
 [24 25 26]]


#Vectorization
doing operations on entire array at once instead of using loops

Vectorization makes it:
-faster
-cleaner code
-less memory usage

In [31]:
#square all numbers
arr=np.array([1,2,3,4])
print(arr**2)

[ 1  4  9 16]


In [32]:
a=np.array([1,2,3])
b=np.array([4,5,6])

print(a+b)

[5 7 9]


In [33]:
#conditional vectorization

arr=np.array([10,20,30,40])
print(arr>25)

[False False  True  True]


In [34]:
#using condition to modify values

arr[arr>25]=100
print(arr)

[ 10  20 100 100]


In [ ]:
#using where

np.where(arr>25,1,0)


array([0, 0, 1, 1])

In [39]:
#mathematical operations

arr=np.array([1,5,3,4])

print(np.sort(arr))
print(np.sqrt(arr))
print(np.log(arr))
print(np.sin(arr))

[1 3 4 5]
[1.         2.23606798 1.73205081 2.        ]
[0.         1.60943791 1.09861229 1.38629436]
[ 0.84147098 -0.95892427  0.14112001 -0.7568025 ]


In [ ]:
#broadcasting +vectorization together

arr=np.array([[1,2,3],
              [4,5,6]])

mean=np.array([2,3,4])

print(arr-mean)

#broadcasting handles shape, vectorization handles operation

[[-1 -1 -1]
 [ 2  2  2]]
